---
title: "PSPL Site Index Conversion: Missing SI Assessment"
output: html_document
---


# PSPL 2022   

2022.dec.15



Start: `r format(Sys.time(),"%c")`

```{r setup, echo=TRUE,message=TRUE,warning=TRUE}

year <- '2022'

library(RPostgreSQL)
library(tidyverse)
library(data.table)
library(ggplot2)
library(kableExtra)

# set up for schema and user
schema <- 'msyt_2022'
opt <- paste0("-c search_path=",schema)
user_name <- 'results'
database <- 'msyt'
con <- dbConnect('PostgreSQL',dbname='msyt',user=user_name,options=opt)





#load the R code for site index conversions


si_convert <- paste0(getwd(),'/site_index_conversion_equations_v3.r')

source(si_convert, local = knitr::knit_global())


kablep <- function (x) {
  kable(x) %>%
  kable_styling(bootstrap_options = c("striped"),full_width=F,font_size=13,position = 'left')
}


```


```{r}


# function to derive where species do no have a site index
assign_missing <- function(d){
  
  
  setDF(d)
  
  # set NA to 0 
  d[is.na(d)] <- 0
  
  # convert 3 char species to 2 char
  # Cwc,Fdc,Hwc
  d$species <- gsub('Cwc','Cw',d$species)
  d$species <- gsub('Cwi','Cw',d$species)
  d$species <- gsub('Fdc','Fd',d$species)
  d$species <- gsub('Fdi','Fd',d$species)
  d$species <- gsub('Hwc','Hw',d$species)
  d$species <- gsub('Hwi','Hw',d$species)
  
  d$missing <- ''
  
  d$missing <- case_when(
    grepl('At',d$species) & d$at_si == 0 ~ 'At',
    TRUE ~ ''
  )
  
  sp <- c('Ba','Bg','Bl','Cw','Dr','Ep','Fd','Hm','Hw','Lt','Lw','Pa','Pl','Pw','Py','Sb','Se','Ss','Sw','Yc')
  
  # use the at_si column as reference
  n <- which(colnames(d)=='at_si')
  #n <- 3
  for (s in sp) {
    
    n <- n + 1
    d$missing <- case_when(
      grepl(s,d$species) & d[,n] == 0 ~ paste0(d$missing,':',s),
      TRUE ~ paste0(d$missing,'')
    )
    
  }
  
  return(d)
  
}



```



# Feature id

```{r  si_convert_fid,echo=TRUE,message=TRUE,warning=TRUE}


# read avg_op_data: table = pspl_site_index_mean_op
# this is the mean value feature_id data

q1 <- paste0('select *  from msyt_',year,'.pspl_site_index_mean_op')
si_data <- dbGetQuery(con,q1)



species <- dbGetQuery(con,"select opening_id,array_to_string(species,',') as species ,b.bec_zone,b.bec_subzone from species_list_op a left join veg_bec_op b using (opening_id)")

#species <- unique(species)

si_data <- left_join(species,si_data,by='opening_id')


# tag the missing species
si_data <- assign_missing(si_data)

tot_row <- nrow(si_data)
tot_valid <- nrow(si_data[si_data$missing =='',])
tot_sw <- nrow(si_data[si_data$missing ==':Sw',])
tot_se <- nrow(si_data[si_data$missing ==':Se',])

df1 <- data.frame('src' = c('Total Valid','Missing Sw','Total'),'n' = c(tot_valid,tot_sw,tot_row),'Percent' = c(as.integer(tot_valid/tot_row*100),as.integer(tot_sw/tot_row*100),100))

kablep(df1)

```

Table 1.  Initial missing site index assessment


```{r}

# fix Sw and Se from Sx
si_data$sw_si <- case_when(
    !si_data$bec_zone %in% c('CDF','CWH','MH') & si_data$bec_zone != 'ESSF' & si_data$sx_si != 0 ~ si_data$sx_si,
    TRUE ~ si_data$sw_si
)

si_data$se_si <- case_when(
    si_data$bec_zone == 'ESSF' & si_data$sx_si != 0 ~ si_data$sx_si,
    TRUE ~ si_data$se_si
)

si_data$ss_si <- case_when(
    si_data$bec_zone %in% c('CDF','CWH','MH') & si_data$sx_si != 0 ~ si_data$sx_si,
    TRUE ~ si_data$ss_si
)

# tag the missing species
si_data <- assign_missing(si_data)


tot_row <- nrow(si_data)
tot_valid <- nrow(si_data[si_data$missing =='',])
tot_sw <- nrow(si_data[si_data$missing ==':Sw',])
tot_se <- nrow(si_data[si_data$missing ==':Se',])

df1 <- data.frame('src' = c('Total Valid','Missing Sw','Total'),'n' = c(tot_valid,tot_sw,tot_row),'Percent' = c(as.integer(tot_valid/tot_row*100),as.integer(tot_sw/tot_row*100),100))


kablep(df1)



```

Table 2.  Correction applied to Sw, Se and Ss

```{r discon}

dbDisconnect(con)

```



End: `r format(Sys.time(),"%c")`