---
title: "Test SI Conversion"
author: "dwaddell"
output: html_document
---


# test for table lookup

2023_feb_06




```{r}


year <- '2022'

library(RPostgreSQL)
library(tidyverse)
library(data.table)
library(ggplot2)
library(kableExtra)

# set up for schema and user
schema <- 'msyt_2022'
opt <- paste0("-c search_path=",schema)
user_name <- 'results'
database <- 'msyt'
#con <- dbConnect('PostgreSQL',dbname='msyt',user=user_name,options=opt)


kablep <- function (x) {
  kable(x) %>%
  kable_styling(bootstrap_options = c("striped"),full_width=F,font_size=13,position = 'left')
}


```


```{r create_data,eval = FALSE}

# base data
# extracted from : copy pspl_site_index_mean_fid to 'c:/data/temp/pspl_site_index_mean_fid.csv' csv header;
fn <- 'C:/Data/temp/pspl_site_index_mean_fid.csv'

# read 2022 data (unconverted)
si_data <- data.table::fread(fn,sep=',')

# subset 
#si_data <- si_data[is.na(fd_si)]
si_data <- sample_n(si_data,20)


si_data$bec_zone <- 'ESSF'
si_data$bec_subzone <- 'mk'

# random set Coast

r <- sample_n(si_data,5)
r$bec_zone <- 'CDF'

si_data <- rbind(si_data,r)

data.table::fwrite(si_data,'c:/data/temp/test_si_data.csv',sep=',',row.names = FALSE)

```


```{r }

#names(si_data) <- c("feature_id","at","ba","bl","cw","fd","hw","lw","pl","sb","se","ss" ,"sw","sx","bec_zone" ) 

#si_data[, c_i:= 'I'][bec_zone %in% c('CDF','CWH','MH'), c_i:='C']





# get first set coefficients

fnc <- paste0(getwd(),'/conversion_coefficients_v1.txt')
coef <- data.table::fread(fnc,sep=',')


# get 1 to 1 coefficients
fnc2 <- paste0(getwd(),'/conversion_coefficients_1_1.txt')
coef_1_1 <- data.table::fread(fnc2,sep=',')




#kable(coef,format="html",caption = 'Table of species site index conversion coefficients') %>%
#kable_styling(bootstrap_options = c("striped"),full_width=F,font_size=13,position = 'left')

```

- s1 = species that requires a site index
- s2 = substitute species to use
- b0 = intercept
- b1 = slope

```{r}



# function to derive where species do no have a site index
assign_missing <- function(d){
  
  # force as data frame to be able to use column locaiton
  setDT(d)
  
  # set NA to 0 
  d[is.na(d)] <- 0
  
  # convert 3 char species to 2 char
  # Cwc,Fdc,Hwc
  d$species <- gsub('Cwc','Cw',d$species)
  d$species <- gsub('Cwi','Cw',d$species)
  d$species <- gsub('Fdc','Fd',d$species)
  d$species <- gsub('Fdi','Fd',d$species)
  d$species <- gsub('Hwc','Hw',d$species)
  d$species <- gsub('Hwi','Hw',d$species)
  
  d$missing <- ''
  
  d$missing <- case_when(
    grepl('At',d$species) & d$at == 0 ~ 'At',
    TRUE ~ ''
  )
  
  sp <- c('Ba','Bg','Bl','Cw','Dr','Ep','Fd','Hm','Hw','Lt','Lw','Pa','Pl','Pw','Py','Sb','Se','Ss','Sw','Yc')
  
  # use the at_si column as reference
  n <- which(colnames(d)=='at')
  #n <- 3
  for (s in sp) {
    
    n <- n + 1
    d$missing <- case_when(
      grepl(s,d$species) & d[,..n] == 0 ~ paste0(d$missing,':',s),
      TRUE ~ paste0(d$missing,'')
    )
    
  }
  
  return(d)
  
}


# function to look up coefficients based on the species that has a zero for site index
# feed it the data table that is a subset of the species
# this looks up the column that holds the data

update_site_index <- function(df,sp) {
  
  # df is the data table
  # sp is the species to be converted
  
  setDT(df)
  
  # dummy column for updating single species site index
  # we are passing by column reference
  df$dummy_si <- 0
  
  # subset for only the species in question
  cx <- coef[coef$s1 == sp,]
  
  # sort for cw, fd, hw
  #if (df$bec_zone %in% c('CDF','CWH','MH') & sp %in% c('cw','fd','hw')){ 
  #    cx <- cx %>% subset(l0 =='c')
  #} else {
  #      cx <- cx %>% subset(l0 == '') 
  #    }
  

  #  loop over the set of coefficients that are available for the species that has a 0 site index
  for (i in 1:nrow(cx)){
    x <- cx[i,]
    df[get(x$s2) > 0 & dummy_si == 0 ,dummy_si := x$b0 + ( x$b1* get(x$s2))]
  }
  
  
  # pass back the site index values
  return(df$dummy_si)
  
}

```

```{r}

# function to look up coefficients based on the species that has a zero for site index
# feed it the data table that is a subset of the species
# this looks up the column that holds the data

update_site_index_1_1 <- function(df,sp) {
  
  setDT(df)
  # dummy column for updating single species site index
  # we are passing by column reference
  df$dummy_si <- 0
  
  # df is the data table
  # sp is the species to be converted
  
  # subset for only the species in question
  cx <- coef_1_1[coef_1_1$s1 == sp,]

  # loop over the set of coefficients that are available for the species that has a 0 site index
  # grab the replacement data from the column name
  for (i in 1:nrow(cx)){
    x <- cx[i,]
    #df[get(x$s2) > 0 & si == 0,si := get(x$s2)]
    df[get(x$s2) > 0,dummy_si := get(x$s2)]
    
  }
  
  # pass back the site index values from the dummy column as a vector

  return(df$dummy_si)
  
}

```




```{r }

# universal update for sw = sx & ss = sx
# does a one to one translation
# coded in the coefficient table as s1 = sz



fn <- paste0(getwd(),'/test_si_data.csv')
fn2 <- paste0(getwd(),'/test_species_data.csv')

# read 2022 data (unconverted)
si_data <- data.table::fread(fn,sep=',')

fid <- si_data$feature_id

#q1 <- glue::glue_sql("select feature_id,array_to_string(species,',') as species ,bec_zone,bec_subzone from species_list_future_fid where feature_id in ({fid*})")
#species <- dbGetQuery(con,q1)

species <- data.table::fread(fn2,sep=',')

si_data <- left_join(si_data,species,by='feature_id')

# all si values NA need to be zero
si_data[is.na(si_data)] <- 0

si_data$bec_zone <- 'ESSF'
si_data$bec_subzone <- 'mk'

si_data$bec_zone[si_data$id> 20] <- 'CDF'



names(si_data) <- c("id","feature_id","at","ba","bg","bl","cw","dr","ep","fd","hm","hw","lt","lw","pa","pl","pw","py","sb","se","ss" ,"sw","sx","yc","species","bec_zone" ,"bec_subzone")



si_data <- assign_missing(si_data)

si_data$src <- 'pspl'

# split

# those that require fixing
fix_si <- si_data %>% subset(missing != '') 
# those that are good
si_data <- si_data %>% subset(!missing != '') 

fix_si$src <- 'spruce_conv'

fix_si$sw[which(fix_si$sw==0) ] <- update_site_index_1_1(fix_si[which(fix_si$sw==0 )],'sw')
fix_si$se[which(fix_si$se==0) ] <- update_site_index_1_1(fix_si[which(fix_si$se==0 )],'se')

#fix_si <- spruce_conversion(fix_si)
fix_si <- assign_missing(fix_si)

# put those that are fixed back into base
si_data <- rbind(si_data,fix_si[fix_si$missing=='',])

# those that require fixing
fix_si <- fix_si %>% subset(missing != '')

fix_si$src <- 'base1'

#x1 <- fix_si[fix_si$id == 1,]
#x1 <- rbind(x1,x1,x1)
#x1$at <- 0
#x1$pl <- 0
#x1$sw <- 0
#x1$id <- c(1,2,3)
#x1$pl[x1$id %in% c(1,3)] <- 1
#x1$sw[x1$id %in% c(2,3)] <- 1
#
#x1$at<- update_site_index(x1,'at')




fix_si$at[which(fix_si$at==0 & grepl('At',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$at==0 & grepl('At',fix_si$missing))],'at')
fix_si$ba[which(fix_si$ba==0 & grepl('Ba',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$ba==0) & grepl('Ba',fix_si$missing) ],'ba')

# there are no coefficients for Bg
#fix_si$bg[which(fix_si$bg==0)] <- update_site_index(fix_si[which(fix_si$bg==0)],'bg')

# bl is assumed to be interior
fix_si$bl[which(fix_si$bl==0  & grepl('Bl',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$bl==0  & grepl('Bl',fix_si$missing) )],'bl')

# cw
fix_si$cw[which(fix_si$cw==0 & !fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Cw',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$cw==0 & !fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Cw',fix_si$missing) )],'cw')

fix_si$cw[which(fix_si$cw==0 & fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Cw',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$cw==0 & fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Cw',fix_si$missing) )],'cwc')

x1 <- fix_si[fix_si$id == 1]
x1$fd[which(x1$fd==0 & !x1$bec_zone %in% c('CDF','CWH','MH')  & grepl('Fd',x1$missing) )] <- update_site_index(x1[which(x1$fd==0 & !x1$bec_zone %in% c('CDF','CWH','MH')  & grepl('Fd',x1$missing) )],'fd')

#fd
fix_si$fd[which(fix_si$fd==0 & !fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Fd',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$fd==0 & !fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Fd',fix_si$missing) )],'fd')
fix_si$fd[which(fix_si$fd==0 & fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Fd',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$fd==0 & fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Fd',fix_si$missing) )],'fdc')

#hw
fix_si$hw[which(fix_si$hw==0 & !fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Hw',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$hw==0 & !fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Hw',fix_si$missing) )],'hw')
fix_si$hw[which(fix_si$hw==0 & fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Hw',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$hw==0 & fix_si$bec_zone %in% c('CDF','CWH','MH')  & grepl('Hw',fix_si$missing) )],'hwc')


fix_si$lw[which(fix_si$lw==0  & grepl('Lw',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$lw==0  & grepl('Lw',fix_si$missing) )],'lw')
fix_si$pl[which(fix_si$pl==0  & grepl('Pl',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$pl==0  & grepl('Pl',fix_si$missing) )],'pl')
fix_si$sb[which(fix_si$sb==0  & grepl('Sb',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$sb==0  & grepl('Sb',fix_si$missing) )],'sb')

fix_si$ss[which(fix_si$ss==0  & grepl('Ss',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$ss==0  & grepl('Ss',fix_si$missing) )],'ss')
fix_si$sw[which(fix_si$sw==0  & grepl('Sw',fix_si$missing) )] <- update_site_index(fix_si[which(fix_si$sw==0  & grepl('Sw',fix_si$missing) )],'sw')

# notes 
# Sx off

fix_si <- assign_missing(fix_si)

si_data <- rbind(si_data,fix_si)

#convert to numeric 1
  si_data <- si_data %>% mutate_if(is.numeric, round, digits=1)


c1 <- count(si_data,src)
c1 <- head(c1,4)

si_data <- si_data %>% select(feature_id,at,ba,bg,bl,cw,dr,ep,fd,hm,hw,lt,lw,pa,pl,pw,py,sb,se,ss,sw,sx,yc,src) %>% arrange(feature_id)

data.table::fwrite(si_data,'v2_t1.csv')

kablep(c1)

```


```{r eval=FALSE}

isTRUE(all.equal(si_data,c1))



# one to one

# one to one conversion
  
  si_data$ba[which(si_data$ba==0)] <- update_site_index_1_1(si_data[which(si_data$ba==0)],'ba' )
  si_data$bl[which(si_data$bl==0)] <- update_site_index_1_1(si_data[which(si_data$bl==0)],'bl' )
  si_data$bg[which(si_data$bg==0)] <- update_site_index_1_1(si_data[which(si_data$bg==0)],'bg' )
  si_data$pw[which(si_data$pw==0)] <- update_site_index_1_1(si_data[which(si_data$pw==0)],'pw' )
  si_data$ss[which(si_data$ss==0)] <- update_site_index_1_1(si_data[which(si_data$ss==0)],'ss' )
  si_data$lt[which(si_data$lt==0)] <- update_site_index_1_1(si_data[which(si_data$lt==0)],'lt' )
  si_data$lw[which(si_data$lw==0)] <- update_site_index_1_1(si_data[which(si_data$lw==0)],'lw' )
  si_data$hm[which(si_data$hm==0)] <- update_site_index_1_1(si_data[which(si_data$hm==0)],'hm' )
  si_data$hw[which(si_data$hw==0)] <- update_site_index_1_1(si_data[which(si_data$hw==0)],'hw' )
  si_data$pa[which(si_data$pa==0)] <- update_site_index_1_1(si_data[which(si_data$pa==0)],'pa' )
  si_data$pl[which(si_data$pl==0)] <- update_site_index_1_1(si_data[which(si_data$pl==0)],'pl' )
  
  # if cwi = 0 and sw >0 cw = sw
  si_data$cw[which(si_data$cw==0 & si_data$c_i =='I')] <- update_site_index_1_1(si_data[which(si_data$cw==0 & si_data$c_i =='I')],'cw')
  
  # py
   si_data$py[which(si_data$py==0 &  si_data$bec=="SBS" & si_data$subzone == "dk")] <- update_site_index_1_1(si_data[which(si_data$py==0 & si_data$bec=="SBS" & si_data$subzone == "dk")],'py')
  



#si_data$dr[which(si_data$dr==0)] <- update_site_index(si_data[which(si_data$dr==0)],'dr')

```

