---
title: "Missing SI Values in an opening"
author: "D. Waddell"
date: "`r Sys.Date()`"
output: html_document
---

```{r init,echo=FALSE,message=FALSE,warning=FALSE}


year <- '2022'

library(RPostgreSQL)
library(tidyverse)
library(data.table)
library(ggplot2)

# set up for schema and user
schema <- 'msyt_2022'
opt <- paste0("-c search_path=",schema)
user_name <- 'results'
database <- 'msyt'
con <- dbConnect('PostgreSQL',dbname='msyt',user=user_name,options=opt)

```

Site index values are derived from PSPL data.  At the feature_id, the BEC is assigned based on the largest contributor. The same applies at an opening level.  

When a feature is contained within an opening, there can be differences between the Opening aggregation of BEC and the feature BEC.    

## Example

Opening -258070000  

### Feature data

```{sql connection=con ,echo=FALSE}

--update si1 set ba_si = NULL where ba_si = 0;
--update si1 set fd_si = NULL where fd_si = 0;
--update si1 set pl_si = NULL where pl_si = 0;
--update si1 set se_si = NULL where se_si = 0;

select  
	opening_id,feature_id,bec_zone,bec_subzone,	ba_si,fd_si,pl_si,se_si,area
from si1 
order by 3,4;

```

Table 1.  

Here we see that the majority of the features are ESSF, with 2 features being IMA.  Also note that the species site index values are all NULL for IMA.  These values will have to be assigned or the GY Model will fail.  

The NULL values are generated in the initial PSPL process.  This generally means that there was no PEM or TEM and that either a Biophysical model doesn't exist for the give BEC or it is outside the paramertization range for the Biophysical model.

___


### Opening Data
```{sql connection=con ,echo=FALSE}

select opening_id, bec_zone,bec_subzone,ba_si,fd_si,pl_si,se_si
from si2 ;
--where opening_id = -258070000;

```

Table 2. 

When the PSPL data is aggregated to the opening (again using largest contributor) we see that the BEC is ESSF.  

___


### BEC aggregate data

```{sql connection=con,echo=FALSE}

--update si3 set ba_si = NULL where ba_si = 0;
--update si3 set fd_si = NULL where fd_si = 0;
--update si3 set pl_si = NULL where pl_si = 0;
--update si3 set se_si = NULL where se_si = 0;

select bec_zone,bec_subzone,ba_si,fd_si,pl_si,se_si from si3;

```

Table 3.  BEC aggregate data

The BEC data from PSPL has no aggregates for IMA.  

This means that we can't use BEC mean values to fill in the gaps.

___

## Discussion

So today's problem is how to fill in the missing values.  




