---
title: "Process Coefficients"
author: "dwaddell"
date: '2022-05-20'
output: html_document
---


## test process for coefficients in table for siteindex conversion



```{r}


library(data.table)


# table of conversion coefficients
coef <- data.table('s1' = c('at','at','sw','sw','sw'),
                   's2' = c('sw','bl','se','fd','bl'),
                   'b0' = c(-1, -2,-3, -4, -5), 
                   'b1' = c(1.1, 1.2, 1.3, 1.4, 1.5))

print(coef)

```

Simple table of coefficients

```{r}

# test data
si_data <- data.table('id' = c(1,2,3,4,5,6,7,8,9,10),
                      'at' = c(0,0,0,0,0,12,14,18,12,14),
                      'bl' = c(0,17,0,17,17,0,5,17,18,19),
                      'fd' = c(21,25,18,22,18,19,21,22,24,0),
                      'sw' = c(15,0,0,0,15,0,0,0,0,0),
                      'se' = c(14,0,0,0,13,12,11,15,0,0))

si_data$si <- 0

print(si_data)

```

Some contrived data

```{r}

# function to look up coefficients based on the species that has a zero for site index
# feed it the data table that is a subset of the species

update_site_index <- function(df,sp) {
  
  # df is the data table
  # sp is the species to be converted
  
  # subset for only the species in question
  cx <- coef[coef$s1 == sp,]

  #  loop over the set of coefficients that are available for the species that has a 0 site index
  for (i in 1:nrow(cx)){
    x <- cx[i,]
    df[get(x$s2) > 0 & si == 0,si := x$b0 + ( x$b1* get(x$s2))]

  }
  
  # pass back the site index values
  return(df$si)
  
}

```

Run the conversion, one species at a time

```{r }

# convert at
si_data$si[which(si_data$at==0)] <- update_site_index(si_data[which(si_data$at==0)],'at')

# convert sw
si_data$si[which(si_data$sw==0)] <- update_site_index(si_data[which(si_data$sw==0)],'sw')




print(si_data)

```