---
title: "Generate Initial PSPL tables"
author: "dwaddell"
date: '2022-05-19'
output: md_document
---


## Generate PSPL point averages

- feature_id
- opening_id

```{r init}

library(RPostgreSQL)

# set up for schema and user
schema <- 'msyt_2022'
opt <- paste0("-c search_path=",schema)



user_name <- 'postgres'
database <- 'msyt'
con <- dbConnect('PostgreSQL',dbname='msyt',user=user_name,options=opt)
#con <- dbConnect('PostgreSQL',dbname='msyt',user=user_name)



db_vac <- function(tb){
  
  com <- shQuote(paste0('vacuum analyze ',tb))
  cmd_arg <- c('-d ' ,database,
                    '-c ' ,com)
  system2('psql', args=cmd_arg,stderr=TRUE)
  
}


```

```{sql connection=con}

drop sequence if exists t1_seq;
create sequence t1_seq;

drop table if exists pspl_init;
drop table if exists pspl_init_t;

select now() as "start create pspl raw initialze";

-- in each unit(n) objectid is unique
-- after the merge, objectid is no longer unique
-- create id as unique
create table pspl_init_t as 
select 
	nextval('t1_seq') as id,	-- unique id,
	feature_id,
	cast(at_si as numeric(5,1)) as at_si,
  cast(ba_si as numeric(5,1)) as ba_si,
  cast(bg_si as numeric(5,1)) as bg_si,
  cast(bl_si as numeric(5,1)) as bl_si,
  cast(cw_si as numeric(5,1)) as cw_si,
  cast(dr_si as numeric(5,1)) as dr_si,
  cast(ep_si as numeric(5,1)) as ep_si,
  cast(fd_si as numeric(5,1)) as fd_si,
  cast(hm_si as numeric(5,1)) as hm_si,
  cast(hw_si as numeric(5,1)) as hw_si,
  cast(lt_si as numeric(5,1)) as lt_si,
  cast(lw_si as numeric(5,1)) as lw_si,
  cast(pa_si as numeric(5,1)) as pa_si,
  cast(pl_si as numeric(5,1)) as pl_si,
  cast(pw_si as numeric(5,1)) as pw_si,
  cast(py_si as numeric(5,1)) as py_si,
  cast(sb_si as numeric(5,1)) as sb_si,
  cast(se_si as numeric(5,1)) as se_si,
  cast(ss_si as numeric(5,1)) as ss_si,
  cast(sw_si as numeric(5,1)) as sw_si,
  cast(sx_si as numeric(5,1)) as sx_si,
  cast(yc_si as numeric(5,1)) as yc_si,
	trim(substring(bgc_label,1,4)) as bec_zone,
	trim(substring(bgc_label,5,3)) as bec_subzone

from pspl_raw 
where feature_id is not NULL;

;


select now() as "create indexes on pspl raw";
 

--create index m_idx_sr1 on pspl_raw using gist(wkb_geometry);
create index m_idx_sr2 on pspl_init_t(feature_id);

```

```{r}

tbl <- paste0(schema,'.pspl_init_t')
db_vac(tbl)



```


```{sql connection = con}

drop sequence t1_seq;

-- add opening from veg_comp
drop table if exists pspl_init;
create table pspl_init as
select
	a.id,
	a.feature_id,
	b.opening_id,
	a.at_si,
	a.ba_si,
	a.bg_si,
	a.bl_si,
	a.cw_si,
	a.dr_si,
	a.ep_si,
	a.fd_si,
	a.hm_si,
	a.hw_si,
	a.lt_si,
	a.lw_si,
	a.pa_si,
	a.pl_si,
	a.pw_si,
	a.py_si,
	a.sb_si,
	a.se_si,
	a.ss_si,
	a.sw_si,
	a.sx_si,
	a.yc_si,
	a.bec_zone,
	a.bec_subzone
from pspl_init_t a
left join veg_comp b using(feature_id)
;

drop table pspl_init_t;

create index idx_pspl1 on pspl_init(feature_id);
create index idx_pspl2 on pspl_init(opening_id);


```

```{r}


tbl <- paste0(schema,'.pspl_init')
db_vac(tbl)

```